---
traefik_user: traefik-user
traefik_version: "v3.0"
acme_email: "pjurke@icloud.com"

# Traefik can't access containers from a different user
# We use the File Provider approach - each service provides its own yml file here
traefik_dynamic_conf_dir: "/opt/traefik/dynamic"